### PR TITLE
A number of coding style cleanups for the netcat kernel module

### PR DESCRIPTION
**Pull request by gregkh**
Some basic whitespace and other formatting tweaks to get the netcat kernel module
to abide by the basic Linux kernel coding style rules.

### CODE REVIEW

**Comment by blucia0a** [comment]
Thanks!  Will test later today and merge these style changes in.

**Comment by gregkh** [comment]
Thanks.  I can add multi-user playback pretty easily on top of this patch series, no need for static variables :)

**Comment by mark-bl** [comment]
After this pull request is accepted I can say I and @gregkh contributed to the same project.
For me that's a win :)

**Comment by blucia0a** [comment]
Thanks a lot, Greg!  I would love to see how to enable multi-user playback.  I haven't done much kernel hacking before, so just getting the original version built was a fun exercise.

**Comment by gregkh** [comment]
Ok, I'll work on it this afternoon, should make the code a bit simpler.

And for a "first time kernel module", it's a very nice job.

**Comment by blucia0a** [comment]
Thanks a lot!  Glad to have your contributions to make our album release better!

**Pull request merged**
