### PR TITLE
Add support for FreeBSD.

### PR DESCRIPTION
**Pull request by grimreaper**
This is a mildly debugged first attempt: there are likely bugs.  Be aware.

### CODE REVIEW

**Comment by grimreaper** [comment]
ugh - I think I missed some refactoring in the Linux version.  This pull request will likely need to be updated

**Comment by pah** [comment]
Indeed, there are no `trk?.h` headers anymore, so the PR won't work as is.  The refactoring to individual track object files should fix the compiler issues on FreeBSD as well (include ordering, etc).

Secondly, the `README.md` needs to be updated to use `-f Makefile.linux` for the Linux build or just skip the renaming and assume Linux by default.

**Comment by grimreaper** [comment]
Yeah, I noticed that after I filed the pull request :\   I'll work on fixing this and resubmit

**Comment by pah** [comment]
Have you seen the FreeBSD porting effort by @f00stx at https://github.com/f00stx/netcat-cpi-kernel-module-bsd/commits/bsd?
Maybe it's a good idea to merge the different approaches and rebase them on the current Linux HEAD.

**Comment by grimreaper** [comment]
@pah I think @f00stx's work is based on some of my original work.  I'll have a new version shortly that addresses the main issues.

**Comment by f00stx** [comment]
@grimreaper Original code came from here, if that's you please let me know and I'll update the README with your github handle!

http://www.opendevs.org/mytuq/request-for-help-netcat-kernel-module-for-freebsd.html

**Comment by grimreaper** [comment]
@f00stx yeah - I'm Eitan :)  I didn't see your answer before.  Did it make it to the mailing list?  Feel free to email me directly so we don't bother @pah and friends anymore.

**Comment by pah** [comment]
@grimreaper, to be clear, I'm merely an interested lurker as well, not part of netcat like @blucia0a and @dbalatero.  I just did the refactoring to the individual track files, which is why I commented on your pull-request. :-)

**Comment by dbalatero** [comment]
You can certainly reopen this pull request and push updated commits to it as you work on it?

**Comment by grimreaper** [comment]
@pah heh okay.  I appreciate the comments.
@dbalatero I ended up opening  #42 - I'm not sure if there was a better way to do that? I pushed to the same branch so I wonder why github doesn't see them as the same.

**Comment by dbalatero** [comment]
@grimreaper Probably because the PR was closed already, so it didn't bother
to update (and assumed you were re-creating a new pull request). If you
leave the PR open you can keep pushing.

**Pull request closed without merging**
