### PR TITLE
added note about other audio players

### PR DESCRIPTION
**Pull request by wxl**
_I_ did the testing ;)

### CODE REVIEW

**Comment by blucia0a** [comment]
Thanks a lot @wxl !  Glad to know we're compatible!

**Comment by wxl** [comment]
> Thanks a lot @wxl ! Glad to know we're compatible!

np! thx for the great tunes!!! you should come down to Eugene sometime
and perform!

**Comment by blucia0a** [comment]
That would be great!  We'll keep our eyes out for any chances to play there.  Do you know of any relevant venues or Eugene bands?

**Comment by wxl** [comment]
> That would be great! We'll keep our eyes out for any chances to play there. Do
> you know of any relevant venues or Eugene bands?

There's an art gallery called ESAP and there's the Boreal, which is a
new club. In the past, the New Zone art gallery would open their doors
to us (where bad luck. played) but that has changed. There's a big
summer fest coming up and there's always the Eugene Noise Fest near the
end of the year. We're a pretty tight knit community here, so if you
want an opportunity, I'm sure I could send out the door and make
something happen. Just say when!

**Comment by dbalatero** [comment]
@wxl rad! Also keep your eyes out for a new Bad Luck album that just got recorded. It's gonna be fat.

**Comment by wxl** [comment]
@dbalatero, jazzed! pun intended! maybe a table and chairs tour could be
in order? i really want to see chemical clock!!!! if we do it during one
of the fests, maybe we could schedule a show and tell regarding the
technical aspects of your work. it goes well beyond kernel modules. ;)

**Pull request merged**
