### PR TITLE
Split track data into multiple object files

### PR DESCRIPTION
**Pull request by jnwatts**
This original goal of this commit was to reduce the time required to compile all of the tracks. While it now takes _longer_ on my Core i7 Duo, my CPUs are now actually maxed at 100%, and disk I/O is fully saturated!

An added benefit, is that this should alleviate memory related crashes in Brandon's compiler, as the compiler only has to deal w/ a handful of ~4MiB and ~70MiB source files instead of a single ~200MiB source file.

Somewhere down the line, tracks could be added a bit more dynamically too ;-)

### CODE REVIEW

**Comment by blucia0a** [comment]
I will look at this this afternoon after I'm out of work.  I like the idea of getting rid of the compiler crash issue with the large data arrays.

**Comment by dbalatero** [comment]
> my CPUs are now actually maxed at 100%, and disk I/O is fully saturated

I see what you did there.

**Comment by jnwatts** [comment]
Thought someone might like that tidbit ;-)

**Comment by blucia0a** [comment]
I'm going to close this for now because it conflicts with a past merge that added multiuser support.  Feel free to fork off the new master and submit another pull request and we can re-evaluate.  Thanks for your interest in our album!

**Pull request closed without merging**
