### PR TITLE
Compile tracks as individual object files

### PR DESCRIPTION
**Pull request by pah**
In order to reduce the memory needs during compilation, this patch series
splits out the tracks into individual object files (`trk?.c`).

Secondly, a `struct netcat_track` is added to a new header `netcat.h`, combining
all track information at one place.

Last, but not least, I've applied the patch from #28 on top of this changeset as well
(to avoid merge conflicts on your side).

I tried to split out the changes into individual steps for easier review.
What do you think?

### CODE REVIEW

**Comment by pah** [comment]
Oh, sorry, I didn't see #17 before.
We now have two "conflicting" implementations, I guess.
@jnwatts, what do you think?

**Comment by jnwatts** [comment]
I think I rather like your use of structs rather than directly pushing the data around as members ;-)

Both of our approaches still use externs however, which I'm still trying to deduce a serviceable work-around for. The best one I've come up w/ so far (but have yet to test) is to build each track as its down loadable module, and set up dependencies such that including netcat.ko requires all of its tracks to be loaded first? Or perhaps vice versa: Until all tracks are loaded netcat could refuse to play?

**Comment by pah** [comment]
Regarding the external symbols, I've at least moved them to the `netcat.h` header now.

The total number of external symbols is not really smaller, if we convert each track to an individual module, though.  I'm not sure, if this is worth the effort?

**Comment by jnwatts** [comment]
Well, the idea behind the separate modules is to allow dynamic registration
if the tracks rather than hard coding their existence into the main module.
Probably is a little silly :-)

**Comment by blucia0a** [comment]
Thanks @pah and @jnwatts  You guys are awesome for sorting out the very long compile time issue with the tracks in separate modules.  Both approaches much appreciated.

**Pull request merged**
