### PR TITLE
As fun as OOMing is, let's use the linker

### PR DESCRIPTION
**Pull request by sjenning**
This commit converts the ogg represented in ascii hex array trk*data.h
format back into binary format and uses the linker to load the binary
data directly into the kernel module object.

Some linker warnings during the module build are, afaict, unavoidable
since there doesn't seem to be a way to do this kind of linking from
within the kernel build environment.

However, the linking of the kernel module with the tracks.o data resolves
those warnings.

Signed-off-by: Seth Jennings spartacus06@gmail.com

### CODE REVIEW

**Comment by blucia0a** [comment]
Hi Seth @spartacus06  thanks for your interest in the project!  We gave it some thought and we're a little wary of including straight .ogg files (as such) in any commits.  We've got high-quality recordings (i.e., not transcoded to death) on http://netcat.bandcamp.com and we wouldn't want these oggs to supplant those in the parts of the internet where music floats around for free.  

Also, we were having fun with this and part of the fun was obfuscating the track data a little bit.  I am going to close this without merging, but I really appreciate your effort to create the pull request and I hope you like listening to the album.

**Comment by sjenning** [comment]
@blucia0a No problem.  I know that having the data in a huge hex array is half the "fun".  For me, I couldn't compile it on a machine with 4G of RAM and 2G swap.  The compiler would get OOM killed. So doing this way, while great for PR, is effectively not buildable for most people.

If you wanted to obfuscate a little, you could rename the ogg files to .o (or whatever extension) and add padding bytes to the beginning so they would not be playable.  Then jump over the padding bytes in the module code.  I know that deobfuscating would be as simple as running dd, but it wasn't much harder even with the data in a huge hex array.  I did it in 40 lines of C.

Your call though :)  Just trying to make it actually buildable for more people (like me).

**Comment by gregkh** [comment]
There's other ways to build this so that the linker doesn't choke on one huge image, and still leave the .h files as-is.  There's been one proposed already, if that doesn't work, I can try my hand at one.

**Comment by pah** [comment]
@gregkh:  Yes, we had a "race" here.  :-( I didn't see #17 (the first "multiple objects" proposal) before and just proposed #34 (another multiple objects implementation).

**Pull request closed without merging**
